### ISSUE TITLE
There seems to be a problem with Vite generation ？

### ISSUE THREAD

**Issue by NicksGhost** [codespikex/vue3-mount#1]
Hello, the following exception occurs when I use Vite to generate, do you know how to solve it?

exec:
`> vue-tsc --noEmit && vite build`

output:
`node_modules/vue3-mount/dist/composable/useMount.d.ts:1:15 - error TS1003: Identifier expected.
import type { default, MountNode } from '../node';
Found 1 error in node_modules/vue3-mount/dist/composable/useMount.d.ts:1`

**Comment by codespikey** [comment]
It should be fixed in the `0.6.4` release.
